// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNLbmR6y0fJxUtHOOis7Sxf-fiQZrvHdI',
    appId: '1:669514170550:web:7af1e7b76215194f2ca617',
    messagingSenderId: '669514170550',
    projectId: 'studybunnies-7967a',
    authDomain: 'studybunnies-7967a.firebaseapp.com',
    databaseURL: 'https://studybunnies-7967a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studybunnies-7967a.appspot.com',
    measurementId: 'G-29S5TZ5K9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC79cCkq8S4XA-NA2HQe6NmaqQCz3aDSE4',
    appId: '1:669514170550:android:45415d8f6397ce542ca617',
    messagingSenderId: '669514170550',
    projectId: 'studybunnies-7967a',
    databaseURL: 'https://studybunnies-7967a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studybunnies-7967a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3DROWgGB3rsNoZPKfjTaqQb6Z1tHAZlA',
    appId: '1:669514170550:ios:a13cddac0bc7dff72ca617',
    messagingSenderId: '669514170550',
    projectId: 'studybunnies-7967a',
    databaseURL: 'https://studybunnies-7967a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'studybunnies-7967a.appspot.com',
    iosBundleId: 'com.example.studybunnies',
  );

}